services:
  amiga_robot:
    image: amiga-ros2:latest
    container_name: amiga_robot
    network_mode: host       
    privileged: true         
    restart: unless-stopped

    runtime: nvidia           # Xavier GPU erişimi
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0       
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix   
      - /mnt/managed_home/farm-ng-user-ertugrulkalkan/amiga-robot/ros2_amiga_ws:/ros2_amiga_ws/src   # kaynak kod canlı mount
      - /mnt/managed_home/farm-ng-user-ertugrulkalkan:/mnt/managed_home/farm-ng-user-ertugrulkalkan  # farm-ng venv + kaynaklar

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0        # RPLidar

    command: bash /ros2_amiga_ws/src/ros2_bridge/src/start_bridge.sh


